server {
    listen 80;

    # Serve React
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API ke Laravel
    location /api {
        proxy_pass http://backend:9000;
        fastcgi_pass backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
    }
}